#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: PG Main Menu
      pause:
        prompt: "\nWelcome to the Reverse Proxy Interface!
                 \nMake a Selection!
    \n\n1. EXIT Interface
    \n2. Deploy Traefik: Reverse Proxy
    \n3. Deploy TLD App: Top Level Domain Application
    \n4. Set CloudFlare for Automatic SubDomain Additions
    \n
    \n------------------------------------------------------
    \n[NOTE: Only Select Option 4 if Traefik Deployed /w CF]
    \n\nType a [NUMBER] Choice & Press [ENTER]"
      register: choice
      until: choice.user_input == "1" or
             choice.user_input == "2" or
             choice.user_input == "3" or
             choice.user_input == "4"
      retries: 99
      delay: 1

    - name: Set Choice
      set_fact:
        fchoice: "{{choice.user_input}}"

    - name: Exiting Interface
      shell: "echo break > /var/plexguide/tldsub.menu"
      when: fchoice == "1"

    - name: Deploy Traefik
      shell: "echo traefik > /var/plexguide/tldsub.menu"
      when: fchoice == "2"

    - name: Deploy TLD App
      shell: "echo tld > /var/plexguide/tldsub.menu"
      when: fchoice == "3"

    - name: Set CloudFlare for Automatic SubDomain Additions!
      shell: "echo cf > /var/plexguide/tldsub.menu"
      when: fchoice == "4"
