#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register Project
      shell: "cat /var/plexguide/pg.number"
      register: serverid

    - name: Installing EDGE
      git:
        repo: "https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server"
        dest: "/opt/plexguide"
        version: Edge
        force: yes
      when: serverid.stdout == "edge"

    - name: "Installing Version {{serverid.stdout}}"
      git:
        repo: "https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server"
        dest: "/opt/plexguide"
        version: "{{serverid.stdout}}"
        force: yes
      when: not serverid.stdout == "edge"
      ignore_errors: True

    - name: "Stops First Time Run"
      shell: "touch /var/plexguide/ask.yes"
      register: program
