#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
  - name: Check DRIVES Service
    stat:
      path: "/root/.config/rclone/rclone.conf"
    register: rclone

  - fail:
      msg: "\nUser Failed to Configure RClone! Exiting!"
    when: rclone.stat.exists == False

  - name: GDrive Check
    shell: grep "gdrive" /root/.config/rclone/rclone.conf
    register: gdrive
    ignore_errors: True

  - fail:
      msg: "\nUser Failed to Configured [gdrive] for RClone"
    when: not gdrive.stdout == "[gdrive]"

  - name: TDrive Check
    shell: grep "tdrive" /root/.config/rclone/rclone.conf
    register: tdrive
    ignore_errors: True

  - fail:
      msg: "\nUser Failed to Configured [tdrive] for RClone"
    when: not tdrive.stdout == "[tdrive]"

  - name: Turning Warning Off
    shell: echo "off" > /var/plexguide/warning.pgblitz
