#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: "Blank Out Server Hash for AppGuard"
  shell: "echo '' > /var/plexguide/server.ht"

- pause:
    prompt: "\nPlease Create a Username!"
  register: appguarduser

- pause:
    prompt: "\nPlease Create a Strong & Rememberable Password"
  register: appguardpw

- pause:
    prompt: "\nUsername: {{appguarduser.user_input}}\nPassword: {{appguardpw.user_input}}\n\nContinue Hash Info and Deploy AppGuard? (Type #)\n1- YES\n2- NO"
  register: exit2
  until: exit2.user_input > "0" and exit2.user_input < "3"
  retries: 99
  delay: 1

- fail:
    msg: "User Opted NOT to CONTINUE! Aborting!"
  when: exit2.user_input != "1"

- name: "Creating Hashed Info"
  shell: "htpasswd -cbs /var/plexguide/server.ht {{appguarduser.user_input}} {{appguardpw.user_input}}"

- name: "Build Container Rebuild Lock"
  shell: "touch /var/plexguide/auth.lock"
