#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- pause:
    prompt: "\nContinue to Deploy AppGuard? (Type #)\n1- No (Exit)\n2- Yes\n3- Disable Appguard\n\nType a [NUMBER] Choice & Press [ENTER]"
  register: exit
  until: exit.user_input > "0" and exit.user_input < "4"
  retries: 99
  delay: 1

- name: Exiting Interface
  shell: "echo break > /var/plexguide/appguard.menu"
  when: exit.user_input == "1"

### Check if AppGuard is Deployed for Disabling ### START
- name: Register Domain
  shell: "cat /var/plexguide/server.ht"
  register: hashtest
  ignore_errors: True
  when: exit.user_input == "3"

- pause:
    prompt: "\nAppGuard is Not Deployed! Exiting"
  when: exit.user_input == "3" and hashtest.stdout == ""

- fail:
    msg: "Exiting - AppGuard is Not Deployed"
  when: exit.user_input == "3" and hashtest.stdout == ""
### Check if AppGuard is Deployed for Disabling ### END

### Blanks out the Variable, just incase
- name: "Build Container Rebuild Lock"
  shell: "echo '' > /var/plexguide/server.ht"
  when: exit.user_input == "3"

### Tells Server to Rebuild Containers
- name: "Build Container Rebuild Lock"
  shell: "touch /var/plexguide/auth.lock"
  when: exit.user_input == "3"

### This is launching the AppGuard Role
- name: Launch AppGuard
  include_tasks: "appguard.yml"
  when: exit.user_input == "2"

- name: Exiting Interface
  shell: "echo break > /var/plexguide/appguard.menu"
