#!/bin/bash
#
# Version:  Ansible-1
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
############################################################# (KEY START)
---
- name: "Establish Key Variables"
  set_fact:
    intport: "5800"
    extport: "5800"
    pgrole: "{{role_name}}"
    image: "jlesage/jdownloader-2"

- name: "Key Variables Recall"
  include_role:
    name: "pgmstart"
    tasks_from: "keyvar.yml"
############################################################# (KEY END)
#
############################################################# (BASICS START)
- name: Create {{pgrole}} directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=yes"
  with_items:
    - "/opt/appdata/{{pgrole}}"
    - "/opt/appdata/{{pgrole}}/config"
    - "/opt/appdata/{{pgrole}}/storage"
    - "{{path.stdout}}/jdownloader"
############################################################# (BASICS END)
- name: "Set Default Volume - {{pgrole}}"
  set_fact:
    default_volumes:
      - "/opt/appdata/{{pgrole}}/config:/config"
      - "{{path.stdout}}/jdownloader:/output"
      - "/opt/appdata/{{pgrole}}/storage:/storage"

- name: "Establish Key Variables - {{pgrole}}"
  set_fact:
    default_env:
      PUID: 1000
      PGID: 1000

- name: "Set Default Labels - {{pgrole}}"
  set_fact:
    default_labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:download.{{domain.stdout}},{{pgrole}}.{{domain.stdout}},{{tldset}}"
      traefik.port: "{{intport}}"

######################## Deploy PGMSTART
- include_role:
    name: "pgmstart"
